import os
nome = input("Nome:")
cpf = float(input("CPF:"))
rg= int(input("RG:"))
datadenascimento=("Data de nascimento:")
sexo=input("Sexo:")
peso=float(input("Peso:"))
tiposanguineo=input("Tipagem sanguinea: ")
renda=float(input("Renda:"))
endereço=input("Endereço:")
telefone=input("Telefone:")
estado=input("Estado:")
cidade=input("Cidade:")

os.system("cls")

print("Nome:",nome)
print("CPF:",cpf)
print("RG:",rg)
print("Data de nascimento:",datadenascimento)
print("Sexo:",sexo)
print("Peso:",peso)
print("Tipagem sanguinea:",tiposanguineo)
print("Renda:",renda)
print("Endereço:",endereço)
print("Telefone:",telefone)
print("Estado:",estado)
print("Cidade:",cidade)